package EquivalenceClasses;

public class NumCommentsSECT4 {
	
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	// 80 comments using normal comments
	

}
